# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
fortran: false
pandoc: false

cache: packages

addons:
  apt:
    packages:
      - cargo
