# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language:
  - r

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
  - export PATH=~/.cargo/bin:$PATH

matrix:
  include:
    - dist: xenial
    - os: osx

cache: packages
latex: false
fortran: false
pandoc: false

cache: packages
