# environment:
#   matrix:
#     - R_VERSION: "patched"
#       RTOOLS_VERSION: 35
#     - R_VERSION: "oldrel"
#       RTOOLS_VERSION: 34

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName C:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host x86_64-pc-windows-gnu
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup target add i686-pc-windows-gnu
  - rustc -V
  - cargo -V

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
