[package]
publish = false
name = "myrustlib"
version = "0.1.0"
authors = ["Dirk Schumacher <mail@dirk-schumacher.net>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
wasmer-runtime = "0.16.0"
wasmer-runtime-core = "0.16.0"
wasmer-runtime-c-api = "0.16.0"
libc = "*"
