# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wasm_init_module <- function() {
    .Call(`_wasmr_wasm_init_module`)
}

wasm_finalize_module <- function(module) {
    invisible(.Call(`_wasmr_wasm_finalize_module`, module))
}

wasm_instantiate <- function(module, bytes, imports) {
    invisible(.Call(`_wasmr_wasm_instantiate`, module, bytes, imports))
}

wasm_call_exported_function <- function(module, fun_name, arguments) {
    .Call(`_wasmr_wasm_call_exported_function`, module, fun_name, arguments)
}

wasm_get_exported_functions <- function(module) {
    .Call(`_wasmr_wasm_get_exported_functions`, module)
}

wasm_get_memory_length <- function(module) {
    .Call(`_wasmr_wasm_get_memory_length`, module)
}

wasm_get_memory_view <- function(module, pointer) {
    .Call(`_wasmr_wasm_get_memory_view`, module, pointer)
}

wasm_grow_memory <- function(module, delta) {
    invisible(.Call(`_wasmr_wasm_grow_memory`, module, delta))
}

